use_frameworks!

platform :ios, '8.0'

target 'PrivateLibraryRepo_Example' do
  pod 'PrivateLibraryRepo', :path => '../'

  target 'PrivateLibraryRepo_Tests' do
    inherit! :search_paths

    
  end
end
